/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface": "#f9f9f9",
        "secondary-fixed-dim": "#e9c400",
        "on-primary-fixed-variant": "#930100",
        "on-background": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#410000",
        "on-error": "#ffffff",
        "inverse-surface": "#2f3131",
        "tertiary-fixed": "#d7e2ff",
        "on-secondary-fixed-variant": "#544600",
        "surface-container-high": "#e8e8e8",
        "on-secondary-fixed": "#221b00",
        "surface-container-low": "#f3f3f3",
        "secondary-container": "#fcd400",
        "on-primary": "#ffffff",
        "primary": "#bc0100",
        "secondary-fixed": "#ffe16d",
        "surface-bright": "#f9f9f9",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffdad4",
        "on-secondary-container": "#6e5c00",
        "surface-container-highest": "#e2e2e2",
        "surface-container": "#eeeeee",
        "secondary": "#705d00",
        "inverse-on-surface": "#f1f1f1",
        "on-surface": "#1a1c1c",
        "inverse-primary": "#ffb4a8",
        "on-secondary": "#ffffff",
        "surface-tint": "#c00100",
        "on-tertiary-container": "#fefcff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dadada",
        "on-tertiary-fixed": "#001a40",
        "on-error-container": "#93000a",
        "tertiary-container": "#0071e8",
        "on-tertiary-fixed-variant": "#004491",
        "primary-fixed-dim": "#ffb4a8",
        "tertiary": "#0059ba",
        "surface-variant": "#e2e2e2",
        "outline": "#956d67",
        "background": "#f9f9f9",
        "on-surface-variant": "#603e39",
        "tertiary-fixed-dim": "#acc7ff",
        "on-primary-container": "#fffbff",
        "outline-variant": "#ebbbb4",
        "primary-container": "#eb0000"
      },
      fontFamily: {
        headline: ['Epilogue', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        label: ['Plus Jakarta Sans', 'sans-serif']
      },
      borderRadius: {
        'xl': '1.5rem',
      }
    },
  },
  plugins: [],
}
